### ISSUE TITLE
A question rather than an issue

### ISSUE THREAD

**Issue by wardmw** [cody1213/twism#1]
Hi Cody,

My apologies for emailing you this way but I could not figure out how to get github the message you in any other way, in fact I am not sure you'll receive this but one hopes.

Basically I have been trying to find out if Twism is limited to either USA and World maps or if it will work with any .svg file that has IDs in it. I ask because I want to create a clickmap of British counties. I nearly have the .svg file (I am updating the object IDs at the moment) but I still need something to actually read the IDs and handle any click requests.

Would your fine software be able to assist me in this?

. |\/|artin

**Comment by cody1213** [comment]
Hi Martin,

It should work with any SVG file.  I've used it in production environments with a variety of custom maps.  There's a customMap setting you can use to define the SVG file to use: 

customMap: 'maps/Map_Of_UK.svg'

If there are any issues, let me know. I've used the plugin in a number of different environments and with a variety of SVG files but haven't tested much with environments/SVG files I didn't set up.  I'll be happy to work out any bugs and also include the UK map in the examples if you want.

**Comment by wardmw** [comment]
Thanks Cody,

Actually any examples using your customMap would really help, I am having
to get up to speed using both jQuery and SVGs so anything that will help
lessen the learning curve would be a real bonus. I think my main issue is
seems to be around handling embedded HTML links in the SVG, or handling
when the user clicks on a specific ID. I can manage a list of IDs and
corresponding HTML links if necesssary but if the HTML links can be
retrieved directly from the CVG then that's one less step for me to code.

|\/|artin

**Comment by wardmw** [comment]
Hey Cody,

In the last couple of hours I have managed to successfully get my own image
up using your twism software and it's looking great, at least from my POV
anyway!  I think the last thing I am having problems with is getting my
head around accessing the svg attributes, specifically the HTML links one I
mentioned above. I am getting something back whihc looks like a pointer to
the information I need ('path1227' or similar refs) but at least it's
progress :-)  If you have any suggestions around these HTML links I would
appreciate it.

|\/|artin

**Comment by cody1213** [comment]
It's hard to say without seeing your code but if you're trying to get HTML attributes from the SVG elements using the ID you added, you can add a click function that does something like this:

$('#SelectorForMap').twism({
  [YOUR CURRENT OPTIONS ARE HERE]
  click: function(geographicAreaId) {
    var someAttributeValue = $('#'+geographicAreaId').attr('TheNameOfYourAttr');
    alert(someAttributeValue);
  }
});

The ID that's passed back to the click and hover options is the same ID as you added to your SVG areas.  While that will work, I wouldn't recommend doing it that way, exactly.  What I usually do is have some JSON data tied to the ID.  So, for instance, on the world map, I'll have something like:

var myData = [
{ id: "us", name: "United States", population: "318.1"},
{ id: "uk", name: "United Kingdom", population: "64.1"}, 
];

Then, when I get the ID from the map using the click (or hover) function, I'm able to get fields from the stored data like this:

  click: function(countryId) {
   var countryData;
    $.each(myData,function( datum ) {
    if ( countryId ==  datum.id) {
      countryData = datum;
      return false
    }
    alert(countryData.population);
  });
  }

If you do that, it makes the code easier to update because you can just swap out the data (or use a dynamically updated source).  

Another tip: the Underscore.js library makes working with JavaScript objects and arrays much quicker and easier. If you have a lot of data, it's worth checking out.
